name: workshop-mcmc
channels:
  - conda-forge
  - bioconda
  - anaconda
  - r
  - defaults
dependencies:
  - r-base=4.0.3
  - jupyterlab=3.0.7
  - r-irkernel=1.1.1
  - r-coda=0.19_4
  - r-dplyr=1.0.4
  - r-ggplot2=3.3.3